version: '3'
services:
  db:
    container_name: postgresql_container
    # image: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    image: node-graphql
    ports:
      - 5000:5000
    depends_on:
      - db
