version: '3'
services:
  db:
    container_name: postgres_container
    # image: postgres
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  app:
    image: graphql-node
    ports:
      - 5000:5000
    depends_on:
      - db
